name: Build Paaws Next.js Application
on: push
jobs:
  build-project:
    name: Build Paaws Next.js Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build Project
        run: npm run build
